# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Posts"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Features"
  pageRef = "features"
  weight = 20

[[main]]
  name = "Discord"
  url = "https://discord.com/invite/GUJkUWymmT"
  weight = 30

[[main]]
  name = "Guides"
  pageRef = "guides"
  weight = 40

[[main]]
  name = "Press"
  url = "https://impress.games/press-kit/gakuenorg/sentou-gakuen-revival"
  weight = 50

[[main]]
  name = "Press Kit"
  parent = "Press"
  url = "https://impress.games/press-kit/gakuenorg/sentou-gakuen-revival"
  weight = 51

[[main]]
  name = "Case Study"
  parent = "Press"
  url = "https://dev.to/godot/online-visual-novel-in-godot-case-study-on-sentou-gakuen-33ce"
  weight = 52

[[main]]
  name = "Developer Spotlight"
  parent = "Press"
  url = "https://www.reddit.com/r/MMORPG/comments/1g3e1pt/online_interactive_visual_novel_sentou_gakuen/"
  weight = 53

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
  identifier = "discord"
  pre = "discord"
  url = "https://discord.gg/GUJkUWymmT"
  weight = 10

 [[footer]]
  identifier = "x-twitter"
  pre = "x-twitter"
  url = "https://x.com/SentouGakuen"
  weight = 20

 [[footer]]
  identifier = "facebook"
  pre = "facebook"
  url = "https://facebook.com/sentougakuen"
  weight = 30

  [[footer]]
  identifier = "youtube"
  pre = "youtube"
  url = "https://www.youtube.com/sentougakuen"
  weight = 40

  [[footer]]
  identifier = "twitch"
  pre = "twitch"
  url = "https://www.twitch.tv/sentougakuen"
  weight = 50